# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import mobmodel_simulator_pb2 as protos_dot_mobmodel__simulator__pb2


class MobilityModelSimulatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.isSimulatorIdle = channel.unary_unary(
                '/pb.MobilityModelSimulatorService/isSimulatorIdle',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                )
        self.tryStartingSimulation = channel.unary_unary(
                '/pb.MobilityModelSimulatorService/tryStartingSimulation',
                request_serializer=protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorConfig.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                )
        self.tryStoppingSimulation = channel.unary_unary(
                '/pb.MobilityModelSimulatorService/tryStoppingSimulation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                )
        self.getSimulatorFrameInfo = channel.unary_unary(
                '/pb.MobilityModelSimulatorService/getSimulatorFrameInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorFrameInfo.FromString,
                )
        self.getSimulatorApproxMap = channel.unary_unary(
                '/pb.MobilityModelSimulatorService/getSimulatorApproxMap',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorApproxMap.FromString,
                )


class MobilityModelSimulatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def isSimulatorIdle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryStartingSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryStoppingSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSimulatorFrameInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSimulatorApproxMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobilityModelSimulatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'isSimulatorIdle': grpc.unary_unary_rpc_method_handler(
                    servicer.isSimulatorIdle,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'tryStartingSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.tryStartingSimulation,
                    request_deserializer=protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorConfig.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'tryStoppingSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.tryStoppingSimulation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'getSimulatorFrameInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.getSimulatorFrameInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorFrameInfo.SerializeToString,
            ),
            'getSimulatorApproxMap': grpc.unary_unary_rpc_method_handler(
                    servicer.getSimulatorApproxMap,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorApproxMap.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.MobilityModelSimulatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MobilityModelSimulatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def isSimulatorIdle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.MobilityModelSimulatorService/isSimulatorIdle',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def tryStartingSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.MobilityModelSimulatorService/tryStartingSimulation',
            protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorConfig.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def tryStoppingSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.MobilityModelSimulatorService/tryStoppingSimulation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getSimulatorFrameInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.MobilityModelSimulatorService/getSimulatorFrameInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorFrameInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getSimulatorApproxMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.MobilityModelSimulatorService/getSimulatorApproxMap',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protos_dot_mobmodel__simulator__pb2.MobilityModelSimulatorApproxMap.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
